version: "3.8"
services:
  sample-db:
    container_name: sample-db
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sample-pass
      MYSQL_DATABASE: sample-db
      MYSQL_USER: sample-user
      MYSQL_PASSWORD: sample-pass
      TZ: 'Asia/Tokyo'